/*DROP TABLE IF EXISTS users CASCADE;*/

CREATE TABLE IF NOT EXISTS users
(
    users_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email    VARCHAR(256)                            NOT NULL,
    name     VARCHAR(256)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (users_id),
    CONSTRAINT uq_users_email UNIQUE (email)
);