version: '3.1'
services:
  stats-server:
    build: statistic/stats-server
    container_name: statistic
    ports:
      - "9090:9090"
      - "9081:9081"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stat-explore
      - SPRING.DATASOURCE.USERNAME=postgres
      - SPRING.DATASOURCE.PASSWORD=Huawei12#$$

  stats-db:
    image: postgres:14-alpine
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stat-explore
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Huawei12#$$

#  ewm-service:
#    ports:
#      - "8080:8080"
#
#  ewm-db:
#    image: postgres:14-alpine
