DROP TABLE IF EXISTS stat CASCADE;

CREATE TABLE IF NOT EXISTS stat
(
    stat_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app       VARCHAR(256)                            NOT NULL,
    uri       VARCHAR(256)                            NOT NULL,
    ip        VARCHAR(256)                            NOT NULL,
    timestamp TIMESTAMP                               NOT NULL,
    CONSTRAINT pk_stat PRIMARY KEY (stat_id)
);